### ISSUE TITLE
will this package get updated to php 8.x and 8.1x

### ISSUE THREAD

**Issue by rabol** [CleanTalk/laravel-antispam#1]
It's all in the subject

**Comment by heddn** [comment]
Yes, it would be nice if it were regularly updated

**Comment by alexandergull** [comment]
Hello. We will inspect this within a several weeks. Thank you for updating.

**Comment by anselmh** [comment]
Hi, is there any news on whether this will get an update or not? If it won’t, this package should likely be marked as archived to make things clear for the users. I’d be very happy to see an update though 🙂

**Comment by Glomberg** [comment]
We have fixed the module and now it was compatible with php 8+
