### ISSUE TITLE
Crash: Undefined variable $general_postdata_test 

### ISSUE THREAD

**Issue by wanderlusted18** [CleanTalk/laravel-antispam#4]
Hello, 

I´m using the 2.0.2 version. My application crashed with the below error message: 

[2023-12-02 07:17:04] prod.ERROR: [laravel-2023-12-02.log](https://github.com/CleanTalk/laravel-antispam/files/13538443/laravel-2023-12-02.log){"exception":"[object] (ErrorException(code: 0): Undefined variable $general_postdata_test at /home/customer/www/gonativeguide.com/gng2-core/vendor/cleantalk/laravel-antispam/src/CleantalkValidate.php:42)
[stacktrace]

These are the lines that the error message refers to: 

```
		// Skip check if
		if(
		    $skip || // Skip flag set by apbct_get_fields_any()
			( ! $sender_email && ! $general_postdata_test ) || // No email detected and general post data test is disabled
			( $registration && ! $registrations_test )
		)
			$skip = true;
```
The issue is not always reproducible, but please try to fix it, as this may mean lost customers for me.  
Please see the complete stacktrace attached.

Thanks, 
W.
[laravel-2023-12-02.log](https://github.com/CleanTalk/laravel-antispam/files/13538439/laravel-2023-12-02.log)

**Comment by svfcode** [comment]
Thanks for error report.

We fixed this and update version to 2.0.3
https://github.com/CleanTalk/laravel-antispam/releases/tag/2.0.3

Please update extension.

Best regards.
