### ISSUE TITLE
Error message: substr(): Argument #1 ($string) must be of type string, array given 

### ISSUE THREAD

**Issue by wanderlusted18** [CleanTalk/laravel-antispam#5]
Hello, 

Unfortunately, my app (using cleantalk/laravel-antispam 2.0.3) crashed again with the below error message: 

Error message: substr(): Argument #1 ($string) must be of type string, array given /home/customer/www/[gonativeguide.com/gng2-core/vendor/cleantalk/laravel-antispam/src/lib/Cleantalk/Antispam/Cleantalk.php](http://gonativeguide.com/gng2-core/vendor/cleantalk/laravel-antispam/src/lib/Cleantalk/Antispam/Cleantalk.php) 409

My business may lose customers due to this error. I attached the stack trace, can you please take a look at it? 

Thanks, 
Örs
[laravel-2023-12-06.log](https://github.com/CleanTalk/laravel-antispam/files/13612434/laravel-2023-12-06.log)

**Comment by svfcode** [comment]
Thanks for error report.

We fixed this and update version to 2.0.4
https://github.com/CleanTalk/laravel-antispam/releases/tag/2.0.4

Please update extension.

Best regards.
